### ISSUE TITLE
No module named 'coco_labels'

### ISSUE THREAD

**Issue by charredchar** [smar000/BlueIris_EnhancedObjectDetect#2]
I have been working on getting your Python 3 version working... and one thing I just can't figure out.

```
Traceback (most recent call last):
  File "bi_alert_detect.py", line 74, in <module>
    import coco_labels as coco
ModuleNotFoundError: No module named 'coco_labels'
```

I can't find anything related to a module named "coco_labels" online, most I find is something about a "coco_labels.txt" which has to do with the object labels. Am I missing something here?

**Comment by smar000** [comment]
Sorry, forgot to add that to the repo. This is basically the coco labels you found, but as a python collection. File added now.

**Comment by charredchar** [comment]
Well that explains my serious confusion! :laughing: Thanks!
