### ISSUE TITLE
AttributeError: module 'config' has no attribute 'DAYS_TO_KEEP_SAVED_IMAGES'

### ISSUE THREAD

**Issue by steppige** [smar000/BlueIris_EnhancedObjectDetect#3]
Hello and thank you for your project that I have been using for 1 year already. But I installed all the blueiris septum from scratch and I encountered this error, can you help me please?

`[DEBUG] Loading previous stationary objects history
[INFO ] 'TF' model initalised
Traceback (most recent call last):
  File "bi_alert_detect.py", line 1093, in <module>
    delete_old_images()
  File "bi_alert_detect.py", line 976, in delete_old_images
    cutoff = now - config.DAYS_TO_KEEP_SAVED_IMAGES * 24 * 60 * 60
AttributeError: module 'config' has no attribute 'DAYS_TO_KEEP_SAVED_IMAGES'`

**Comment by smar000** [comment]
Hi

Add the parameter DAYS_TO_KEEP_SAVED_IMAGES to your config file, with the number of days you want to keep your images, e.g.

DAYS_TO_KEEP_SAVED_IMAGES = 3
